/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CsaeRouteImport } from './routes/csae'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as VerifiedRouteImport } from './routes/verified'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedChatMatchIdRouteImport } from './routes/_authenticated/chat.$matchId'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack.webhook'
import { Route as ApiPublicRevenuecatWebhookRouteImport } from './routes/api/public/revenuecat.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CsaeRoute = CsaeRouteImport.update({
  id: '/csae',
  path: '/csae',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedRoute = VerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatMatchIdRoute =
  AuthenticatedChatMatchIdRouteImport.update({
    id: '/chat/$matchId',
    path: '/chat/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRevenuecatWebhookRoute =
  ApiPublicRevenuecatWebhookRouteImport.update({
    id: '/api/public/revenuecat/webhook',
    path: '/api/public/revenuecat/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/csae': typeof CsaeRoute
  '/delete-account': typeof DeleteAccountRoute
  '/guide': typeof GuideRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/verified': typeof VerifiedRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/revenuecat/webhook': typeof ApiPublicRevenuecatWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/csae': typeof CsaeRoute
  '/delete-account': typeof DeleteAccountRoute
  '/guide': typeof GuideRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/verified': typeof VerifiedRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/revenuecat/webhook': typeof ApiPublicRevenuecatWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/csae': typeof CsaeRoute
  '/delete-account': typeof DeleteAccountRoute
  '/guide': typeof GuideRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/verified': typeof VerifiedRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/revenuecat/webhook': typeof ApiPublicRevenuecatWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/csae'
    | '/delete-account'
    | '/guide'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/upgrade'
    | '/verified'
    | '/chats'
    | '/profile'
    | '/radar'
    | '/chat/$matchId'
    | '/api/public/paystack/webhook'
    | '/api/public/revenuecat/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/csae'
    | '/delete-account'
    | '/guide'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/upgrade'
    | '/verified'
    | '/chats'
    | '/profile'
    | '/radar'
    | '/chat/$matchId'
    | '/api/public/paystack/webhook'
    | '/api/public/revenuecat/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/csae'
    | '/delete-account'
    | '/guide'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/upgrade'
    | '/verified'
    | '/_authenticated/chats'
    | '/_authenticated/profile'
    | '/_authenticated/radar'
    | '/_authenticated/chat/$matchId'
    | '/api/public/paystack/webhook'
    | '/api/public/revenuecat/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CsaeRoute: typeof CsaeRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  GuideRoute: typeof GuideRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  UpgradeRoute: typeof UpgradeRoute
  VerifiedRoute: typeof VerifiedRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicRevenuecatWebhookRoute: typeof ApiPublicRevenuecatWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csae': {
      id: '/csae'
      path: '/csae'
      fullPath: '/csae'
      preLoaderRoute: typeof CsaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified': {
      id: '/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$matchId': {
      id: '/_authenticated/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof AuthenticatedChatMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/revenuecat/webhook': {
      id: '/api/public/revenuecat/webhook'
      path: '/api/public/revenuecat/webhook'
      fullPath: '/api/public/revenuecat/webhook'
      preLoaderRoute: typeof ApiPublicRevenuecatWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedChatMatchIdRoute: typeof AuthenticatedChatMatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedChatMatchIdRoute: AuthenticatedChatMatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CsaeRoute: CsaeRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  GuideRoute: GuideRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  UpgradeRoute: UpgradeRoute,
  VerifiedRoute: VerifiedRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicRevenuecatWebhookRoute: ApiPublicRevenuecatWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
